# docker-compose.yml
version: "3.8"

services:

  fastapiapp:
    build: .
    container_name: rabit_git_action
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672/
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: ecom-rabbit
    ports:
      - "5672:5672"    # AMQP protocol port (your code talks to this)
      - "15672:15672"  # Management UI (browser)
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: