name: Secrets Test

on:
    push:
        branches: [main]

jobs:
    verify-secrets:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Simulate FastAPI startup with secrets
              env:
                STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
                DATABASE_URL: ${{secrets.DATABASE_URL}}
              run:
                echo "Checking if secrets are present"
                if [ -z "$STRIPE_SECRET_KEY" ]; then
                    echo "STRIPE_SECRET_KEY is not set"
                fi
                echo  $STRIPE_SECRET_KEY
                if [ -z "$DATABASE_URL" ]; then
                    echo "DATABASE_URL is not set"
                fi
                echo  $DATABASE_URL
